Repository CRUDE-HI/travel-crew-server, pull requests merged in 2023-10, with the labels that each got.

#16 [feat] 동행 글작성 및 삭제 및 수정
  src/main/java/com/crude/travelcrew/domain/board/contents/CrewGender.java
  src/main/java/com/crude/travelcrew/domain/board/contents/CrewStatus.java
  src/main/java/com/crude/travelcrew/domain/board/controller/PostsController.java
  src/main/java/com/crude/travelcrew/domain/board/dto/PostsReq.java
  src/main/java/com/crude/travelcrew/domain/board/dto/PostsRes.java
  src/main/java/com/crude/travelcrew/domain/board/entity/Posts.java
  src/main/java/com/crude/travelcrew/domain/board/repository/PostsRepository.java
  src/main/java/com/crude/travelcrew/domain/board/service/PostsService.java
Labels: feature

#22 [feat] 여행 기록 수정
  src/main/java/com/crude/travelcrew/domain/awss3/service/AwsS3ServiceImpl.java
  src/main/java/com/crude/travelcrew/domain/travelrecord/controller/TravelRecordController.java
  src/main/java/com/crude/travelcrew/domain/travelrecord/model/dto/EditTravelRecordRes.java
  src/main/java/com/crude/travelcrew/domain/travelrecord/model/entity/TravelRecord.java
  src/main/java/com/crude/travelcrew/domain/travelrecord/service/TravelRecordService.java
  src/main/java/com/crude/travelcrew/domain/travelrecord/service/TravelRecordServiceImpl.java
  src/main/java/com/crude/travelcrew/global/error/type/CommonErrorCode.java
  src/main/java/com/crude/travelcrew/global/error/type/TravelRecordErrorCode.java
Labels: feature

#20 [feat] 회원정보(닉네임,비밀번호) 수정
  src/main/java/com/crude/travelcrew/domain/member/controller/MyPageController.java
  src/main/java/com/crude/travelcrew/domain/member/dto/UpdateNickReq.java
  src/main/java/com/crude/travelcrew/domain/member/dto/UpdatePWReq.java
  src/main/java/com/crude/travelcrew/domain/member/service/MyPageService.java
Labels: feature

#29 [feat] 여행 기록 좋아요 등록 및 취소
  src/main/java/com/crude/travelcrew/domain/travelrecord/controller/TravelRecordHeartController.java
  src/main/java/com/crude/travelcrew/domain/travelrecord/model/entity/TravelRecordHeart.java
  src/main/java/com/crude/travelcrew/domain/travelrecord/repository/TravelRecordHeartRepository.java
  src/main/java/com/crude/travelcrew/domain/travelrecord/service/TravelRecordHeartService.java
  src/main/java/com/crude/travelcrew/domain/travelrecord/service/TravelRecordHeartServiceImpl.java
  src/main/java/com/crude/travelcrew/global/error/type/TravelRecordErrorCode.java
Labels: feature

#30 [feat] 동행 게시판 참가자 리스트 entity 추가
  src/main/java/com/crude/travelcrew/domain/board/dto/MemberListReq.java
  src/main/java/com/crude/travelcrew/domain/board/dto/MemberListRes.java
  src/main/java/com/crude/travelcrew/domain/board/entity/Posts.java
  src/main/java/com/crude/travelcrew/domain/board/service/MemberListService.java
  src/main/java/com/crude/travelcrew/domain/member/entity/Member.java
Labels: feature

#38 feat : 회원 프로필 이미지 업로드
  src/main/java/com/crude/travelcrew/domain/member/controller/MyPageController.java
  src/main/java/com/crude/travelcrew/domain/member/service/MyPageService.java
Labels: feature

#36 feat: 동행 글에 댓글 조회, 등록, 수정, 삭제 기능 추가
  src/main/java/com/crude/travelcrew/domain/board/controller/PostsController.java
  src/main/java/com/crude/travelcrew/domain/board/dto/CommentReq.java
  src/main/java/com/crude/travelcrew/domain/board/dto/CommentRes.java
  src/main/java/com/crude/travelcrew/domain/board/entity/Comment.java
  src/main/java/com/crude/travelcrew/domain/board/repository/CommentRepository.java
  src/main/java/com/crude/travelcrew/domain/board/service/PostsService.java
Labels: feature

#40 [feat] 댓글 작성, 수정, 삭제
  src/main/java/com/crude/travelcrew/domain/travelrecord/controller/TravelRecordCommentController.java
  src/main/java/com/crude/travelcrew/domain/travelrecord/model/dto/TravelRecordCommentReq.java
  src/main/java/com/crude/travelcrew/domain/travelrecord/model/dto/TravelRecordCommentRes.java
  src/main/java/com/crude/travelcrew/domain/travelrecord/model/entity/TravelRecordComment.java
  src/main/java/com/crude/travelcrew/domain/travelrecord/repository/TravelRecordCommentRepository.java
  src/main/java/com/crude/travelcrew/domain/travelrecord/repository/custom/CustomTravelRecordCommentRepository.java
  src/main/java/com/crude/travelcrew/domain/travelrecord/repository/custom/CustomTravelRecordCommentRepositoryImpl.java
  src/main/java/com/crude/travelcrew/domain/travelrecord/service/TravelRecordCommentService.java
  src/main/java/com/crude/travelcrew/domain/travelrecord/service/TravelRecordCommentServiceImpl.java
  src/main/java/com/crude/travelcrew/domain/travelrecord/service/TravelRecordServiceImpl.java
  src/main/java/com/crude/travelcrew/global/error/type/TravelRecordErrorCode.java
Labels: feature

#44 [fix] 작성자 dto에 추가
  src/main/java/com/crude/travelcrew/domain/board/dto/PostsRes.java
Labels: fix

#42 [feat] 사용자 신고하기 기능 추가
  src/main/java/com/crude/travelcrew/domain/member/entity/MemberProfile.java
  src/main/java/com/crude/travelcrew/domain/report/controller/ReportController.java
  src/main/java/com/crude/travelcrew/domain/report/model/dto/ReportReq.java
  src/main/java/com/crude/travelcrew/domain/report/model/dto/ReportRes.java
  src/main/java/com/crude/travelcrew/domain/report/model/entity/Report.java
  src/main/java/com/crude/travelcrew/domain/report/repository/ReportRepository.java
  src/main/java/com/crude/travelcrew/domain/report/service/ReportService.java
Labels: feature

#39 [feat] Crew 오류 처리 클래스 생성 및 구인 글 댓글 오류 처리 수정
  src/main/java/com/crude/travelcrew/domain/board/service/PostsService.java
  src/main/java/com/crude/travelcrew/global/error/exception/CrewException.java
  src/main/java/com/crude/travelcrew/global/error/type/CrewErrorCode.java
Labels: feature

#47 [feat] 여행 게시물 스크랩 기능 구현
  src/main/java/com/crude/travelcrew/domain/board/controller/ScrapController.java
  src/main/java/com/crude/travelcrew/domain/board/entity/Scraps.java
  src/main/java/com/crude/travelcrew/domain/board/repository/ScrapRepository.java
  src/main/java/com/crude/travelcrew/domain/board/service/ScrapService.java
Labels: feature, emergency

#50 [refactor] 회원정보수정 코드 수정
  src/main/java/com/crude/travelcrew/domain/member/controller/MyPageController.java
  src/main/java/com/crude/travelcrew/domain/member/service/MyPageService.java
Labels: refactor, emergency

#53 [feat] 내가 작성한 동행 글 조회
  src/main/java/com/crude/travelcrew/domain/board/dto/PostsRes.java
  src/main/java/com/crude/travelcrew/domain/board/entity/Posts.java
  src/main/java/com/crude/travelcrew/domain/board/repository/PostsRepository.java
  src/main/java/com/crude/travelcrew/domain/board/service/PostsService.java
  src/main/java/com/crude/travelcrew/domain/member/controller/MyPageController.java
  src/main/java/com/crude/travelcrew/domain/member/service/MyPageService.java
Labels: feature, fix

#61 [fix] 동행 게시글 조회, 검색 수정
  src/main/java/com/crude/travelcrew/domain/crew/controller/CrewController.java
  src/main/java/com/crude/travelcrew/domain/crew/model/dto/CrewListRes.java
  src/main/java/com/crude/travelcrew/domain/crew/service/CrewService.java
  src/main/java/com/crude/travelcrew/domain/member/controller/MemberController.java
Labels: fix

#63 [feat] 관리자 페이지 생성
  src/main/java/com/crude/travelcrew/domain/administer/controller/AdminController.java
  src/main/java/com/crude/travelcrew/domain/administer/dto/adminMember/ADUpdateMemberReq.java
  src/main/java/com/crude/travelcrew/domain/administer/dto/getMember/ADGetMemberRes.java
  src/main/java/com/crude/travelcrew/domain/administer/dto/getMember/ADGetRecordRes.java
  src/main/java/com/crude/travelcrew/domain/administer/dto/getMember/ADGetReportRes.java
  src/main/java/com/crude/travelcrew/domain/administer/dto/getMember/ADMemberListReq.java
  src/main/java/com/crude/travelcrew/domain/administer/dto/getMember/ADMemberListRes.java
  src/main/java/com/crude/travelcrew/domain/administer/dto/getMember/ADMemberListResponseDto.java
  src/main/java/com/crude/travelcrew/domain/administer/dto/getRecord/ADRecordListReq.java
  src/main/java/com/crude/travelcrew/domain/administer/dto/getRecord/ADRecordListRes.java
  src/main/java/com/crude/travelcrew/domain/administer/dto/getRecord/ADRecordListResponseDto.java
  src/main/java/com/crude/travelcrew/domain/administer/dto/getReport/ADReportListReq.java
  src/main/java/com/crude/travelcrew/domain/administer/dto/getReport/ADReportListRes.java
  src/main/java/com/crude/travelcrew/domain/administer/dto/getReport/ADReportListResponseDto.java
  src/main/java/com/crude/travelcrew/domain/administer/dto/getReport/ADReportedMemberListReq.java
  src/main/java/com/crude/travelcrew/domain/administer/service/AdminGetMemberService.java
  src/main/java/com/crude/travelcrew/domain/administer/service/AdminGetRecordService.java
  src/main/java/com/crude/travelcrew/domain/administer/service/AdminGetReportService.java
  src/main/java/com/crude/travelcrew/domain/administer/service/AdminMemberService.java
  src/main/java/com/crude/travelcrew/domain/member/model/entity/Member.java
  src/main/java/com/crude/travelcrew/domain/member/model/entity/MemberProfile.java
  src/main/java/com/crude/travelcrew/domain/member/repository/MemberRepository.java
  src/main/java/com/crude/travelcrew/domain/member/repository/custom/CustomMemberRepository.java
  src/main/java/com/crude/travelcrew/domain/member/repository/custom/CustomMemberRepositoryImpl.java
  src/main/java/com/crude/travelcrew/domain/record/model/entity/Record.java
  src/main/java/com/crude/travelcrew/domain/report/repository/ReportRepository.java
  src/main/java/com/crude/travelcrew/domain/report/repository/custom/CustomReportRepository.java
  src/main/java/com/crude/travelcrew/domain/report/repository/custom/CustomReportRepositoryImpl.java
Labels: feature

#59 [rename] CrewScrap 파일 이름 오타 수정
  src/main/java/com/crude/travelcrew/domain/crew/model/entity/CrewScrap.java
  src/main/java/com/crude/travelcrew/domain/crew/service/CrewScrapService.java
Labels: rename

#65 [fix] 관리자 페이지 컨트롤러 오입력 수정
  src/main/java/com/crude/travelcrew/domain/administer/controller/AdminController.java
Labels: fix

#57 [feat] 회원 프로필 이미지 삭제
  src/main/java/com/crude/travelcrew/domain/member/controller/MyPageController.java
  src/main/java/com/crude/travelcrew/domain/member/repository/MemberRepository.java
  src/main/java/com/crude/travelcrew/domain/member/service/MyPageService.java
Labels: feature

#72 [feat] 동행 신청한 회원 목록 조회 구현
  src/main/java/com/crude/travelcrew/domain/crew/controller/CrewMemberController.java
  src/main/java/com/crude/travelcrew/domain/crew/model/dto/CrewMemberRes.java
  src/main/java/com/crude/travelcrew/domain/crew/repository/CrewMemberRepository.java
  src/main/java/com/crude/travelcrew/domain/crew/repository/custom/CustomCrewMemberRepository.java
  src/main/java/com/crude/travelcrew/domain/crew/repository/custom/CustomCrewMemberRepositoryImpl.java
  src/main/java/com/crude/travelcrew/domain/crew/service/CrewMemberService.java
  src/main/java/com/crude/travelcrew/domain/crew/service/CrewMemberServiceImpl.java
Labels: feature

#77 [feat] 내 정보 상세 조회, 다른 회원 정보 상세 조회, 내가 스크랩한 동행글 조회
  src/main/java/com/crude/travelcrew/domain/crew/model/entity/CrewScrap.java
  src/main/java/com/crude/travelcrew/domain/crew/repository/CrewScrapRepository.java
  src/main/java/com/crude/travelcrew/domain/member/controller/MemberController.java
  src/main/java/com/crude/travelcrew/domain/member/controller/MyPageController.java
  src/main/java/com/crude/travelcrew/domain/member/model/dto/MemberRes.java
  src/main/java/com/crude/travelcrew/domain/member/model/entity/Member.java
  src/main/java/com/crude/travelcrew/domain/member/repository/MemberRepository.java
  src/main/java/com/crude/travelcrew/domain/member/service/MemberService.java
  src/main/java/com/crude/travelcrew/domain/member/service/MyPageService.java
Labels: feature

#80 [Fix]동행 글 수정 삭제
  src/main/java/com/crude/travelcrew/domain/crew/controller/CrewController.java
  src/main/java/com/crude/travelcrew/domain/crew/model/constants/CrewGender.java
  src/main/java/com/crude/travelcrew/domain/crew/model/constants/CrewPlace.java
  src/main/java/com/crude/travelcrew/domain/crew/model/dto/CrewReq.java
  src/main/java/com/crude/travelcrew/domain/crew/model/dto/CrewRes.java
  src/main/java/com/crude/travelcrew/domain/crew/model/entity/Crew.java
  src/main/java/com/crude/travelcrew/domain/crew/repository/CrewCommentRepository.java
  src/main/java/com/crude/travelcrew/domain/crew/service/CrewService.java
  src/main/java/com/crude/travelcrew/global/error/type/CrewErrorCode.java
Labels: fix

#86 [fix] 관리자 페이지 폴더 구조 재배치
  src/main/java/com/crude/travelcrew/domain/administer/controller/AdminController.java
  src/main/java/com/crude/travelcrew/domain/administer/dto/getRecord/ADGetRecordRes.java
  src/main/java/com/crude/travelcrew/domain/administer/dto/getReport/ADGetReportRes.java
  src/main/java/com/crude/travelcrew/domain/administer/service/AdminGetRecordService.java
  src/main/java/com/crude/travelcrew/domain/administer/service/AdminGetReportService.java
Labels: fix

#97 [refactor] 내가 작성한 동행글 목록 조회 맵핑 URL 변경
  src/main/java/com/crude/travelcrew/domain/member/controller/MyPageController.java
Labels: refactor

#87 [feat] 내가 쓴 여행기록 게시물 조회
  src/main/java/com/crude/travelcrew/domain/member/controller/MyPageController.java
  src/main/java/com/crude/travelcrew/domain/member/service/MyPageService.java
  src/main/java/com/crude/travelcrew/domain/record/model/dto/EditRecordRes.java
  src/main/java/com/crude/travelcrew/domain/record/model/dto/MyRecordRes.java
  src/main/java/com/crude/travelcrew/domain/record/model/entity/Record.java
  src/main/java/com/crude/travelcrew/domain/record/repository/RecordRepository.java
Labels: feature

#108 [feat] 여행기록 댓글 조회
  src/main/java/com/crude/travelcrew/domain/record/controller/RecordCommentController.java
  src/main/java/com/crude/travelcrew/domain/record/model/dto/RecordCommentListRes.java
  src/main/java/com/crude/travelcrew/domain/record/repository/RecordCommentRepository.java
  src/main/java/com/crude/travelcrew/domain/record/service/RecordCommentService.java
  src/main/java/com/crude/travelcrew/domain/record/service/RecordCommentServiceImpl.java
Labels: feature

#84 [feat] : 내가 신청한 여행 동행 목록
  src/main/java/com/crude/travelcrew/domain/crew/repository/CrewMemberRepository.java
  src/main/java/com/crude/travelcrew/domain/member/controller/MyPageController.java
  src/main/java/com/crude/travelcrew/domain/member/service/MyPageService.java
Labels: feature

#92 [fix] 댓글 등록, 수정 관련 코드 수정
  src/main/java/com/crude/travelcrew/domain/crew/controller/CrewController.java
Labels: fix

#90 [feat] 회원 인증 및 인가
  src/main/java/com/crude/travelcrew/domain/administer/service/AdminMemberService.java
  src/main/java/com/crude/travelcrew/domain/crew/service/CrewMemberServiceImpl.java
  src/main/java/com/crude/travelcrew/domain/crew/service/CrewScrapService.java
  src/main/java/com/crude/travelcrew/domain/crew/service/CrewService.java
  src/main/java/com/crude/travelcrew/domain/member/controller/MemberController.java
  src/main/java/com/crude/travelcrew/domain/member/model/constants/MemberRole.java
  src/main/java/com/crude/travelcrew/domain/member/model/dto/LoginReq.java
  src/main/java/com/crude/travelcrew/domain/member/model/dto/LoginRes.java
  src/main/java/com/crude/travelcrew/domain/member/model/dto/ReissueRes.java
  src/main/java/com/crude/travelcrew/domain/member/model/dto/SignUpRes.java
  src/main/java/com/crude/travelcrew/domain/member/repository/MemberRepository.java
  src/main/java/com/crude/travelcrew/domain/member/service/MemberService.java
  src/main/java/com/crude/travelcrew/domain/member/service/MyPageService.java
  src/main/java/com/crude/travelcrew/domain/record/service/RecordCommentServiceImpl.java
  src/main/java/com/crude/travelcrew/domain/record/service/RecordHeartServiceImpl.java
  src/main/java/com/crude/travelcrew/domain/record/service/RecordServiceImpl.java
  src/main/java/com/crude/travelcrew/domain/report/service/ReportService.java
  src/main/java/com/crude/travelcrew/global/config/JpaConfig.java
  src/main/java/com/crude/travelcrew/global/config/RedisConfig.java
  src/main/java/com/crude/travelcrew/global/config/SecurityConfig.java
  src/main/java/com/crude/travelcrew/global/error/type/CommonErrorCode.java
  src/main/java/com/crude/travelcrew/global/error/type/MemberErrorCode.java
  src/main/java/com/crude/travelcrew/global/security/CustomUserDetails.java
  src/main/java/com/crude/travelcrew/global/security/JwtAuthFilter.java
  src/main/java/com/crude/travelcrew/global/security/JwtProvider.java
  src/main/java/com/crude/travelcrew/global/security/handler/CustomAccessDeniedHandler.java
  src/main/java/com/crude/travelcrew/global/security/handler/CustomAuthenticationEntryPoint.java
  src/main/java/com/crude/travelcrew/global/security/jwt/JwtAuthFilter.java
  src/main/java/com/crude/travelcrew/global/security/jwt/JwtProvider.java
  src/main/java/com/crude/travelcrew/global/security/jwt/model/BlockAccessToken.java
  src/main/java/com/crude/travelcrew/global/security/jwt/model/RefreshToken.java
  src/main/java/com/crude/travelcrew/global/security/jwt/repository/BlockAccessTokenRepository.java
  src/main/java/com/crude/travelcrew/global/security/jwt/repository/RefreshTokenRepository.java
  src/main/java/com/crude/travelcrew/global/security/service/CustomUserDetailsService.java
  src/main/java/com/crude/travelcrew/global/util/AuthUser.java
Labels: feature, refactor

#103 [feat] 여행기록 전체 글 조회
  src/main/java/com/crude/travelcrew/domain/record/controller/RecordController.java
  src/main/java/com/crude/travelcrew/domain/record/model/dto/RecordListRes.java
  src/main/java/com/crude/travelcrew/domain/record/repository/RecordRepository.java
  src/main/java/com/crude/travelcrew/domain/record/service/RecordService.java
  src/main/java/com/crude/travelcrew/domain/record/service/RecordServiceImpl.java
Labels: feature

#110 [feat] 관리자 페이지 여행기록 댓글조회
  src/main/java/com/crude/travelcrew/domain/administer/controller/AdminController.java
  src/main/java/com/crude/travelcrew/domain/administer/dto/getCrew/ADCrewListReq.java
  src/main/java/com/crude/travelcrew/domain/administer/dto/getCrew/ADCrewListRes.java
  src/main/java/com/crude/travelcrew/domain/administer/dto/getCrew/ADCrewListResponseDto.java
  src/main/java/com/crude/travelcrew/domain/administer/dto/getCrew/ADGetCrewRes.java
  src/main/java/com/crude/travelcrew/domain/administer/service/AdminGetCrewService.java
  src/main/java/com/crude/travelcrew/domain/administer/service/AdminGetRecordService.java
  src/main/java/com/crude/travelcrew/domain/crew/model/entity/Crew.java
  src/main/java/com/crude/travelcrew/domain/crew/model/entity/CrewComment.java
  src/main/java/com/crude/travelcrew/domain/record/model/entity/RecordComment.java
Labels: feature

#89 [feat] 회원탈퇴 기능 구현
  src/main/java/com/crude/travelcrew/domain/member/controller/MyPageController.java
  src/main/java/com/crude/travelcrew/domain/member/model/constants/MemberRole.java
  src/main/java/com/crude/travelcrew/domain/member/model/constants/ProviderType.java
  src/main/java/com/crude/travelcrew/domain/member/model/dto/WithDrawPW.java
  src/main/java/com/crude/travelcrew/domain/member/model/entity/Member.java
  src/main/java/com/crude/travelcrew/domain/member/service/MyPageService.java
Labels: feature

#94 [fix] 동행 글 작성 수정, 글수정 수정
  src/main/java/com/crude/travelcrew/domain/crew/controller/CrewController.java
  src/main/java/com/crude/travelcrew/domain/crew/model/constants/CrewMemberStatus.java
  src/main/java/com/crude/travelcrew/domain/crew/model/dto/CrewRes.java
  src/main/java/com/crude/travelcrew/domain/crew/model/entity/Crew.java
  src/main/java/com/crude/travelcrew/domain/crew/service/CrewService.java
  src/main/java/com/crude/travelcrew/domain/member/service/MyPageService.java
Labels: fix

#114 [fix] pull 이후 오류 해결
  src/main/java/com/crude/travelcrew/domain/administer/service/AdminMemberService.java
  src/main/java/com/crude/travelcrew/domain/crew/controller/CrewController.java
  src/main/java/com/crude/travelcrew/domain/crew/service/CrewMemberServiceImpl.java
  src/main/java/com/crude/travelcrew/domain/crew/service/CrewService.java
  src/main/java/com/crude/travelcrew/domain/member/controller/MemberController.java
  src/main/java/com/crude/travelcrew/domain/member/controller/MyPageController.java
  src/main/java/com/crude/travelcrew/domain/member/model/constants/MemberRole.java
  src/main/java/com/crude/travelcrew/domain/member/service/MemberService.java
  src/main/java/com/crude/travelcrew/domain/member/service/MyPageService.java
  src/main/java/com/crude/travelcrew/domain/record/controller/RecordCommentController.java
  src/main/java/com/crude/travelcrew/domain/record/controller/RecordController.java
  src/main/java/com/crude/travelcrew/domain/record/service/RecordHeartServiceImpl.java
  src/main/java/com/crude/travelcrew/domain/record/service/RecordServiceImpl.java
  src/main/java/com/crude/travelcrew/domain/report/controller/ReportController.java
  src/main/java/com/crude/travelcrew/domain/report/repository/custom/CustomReportRepositoryImpl.java
  src/main/java/com/crude/travelcrew/global/security/jwt/JwtProvider.java
Labels: fix, style

#113 [fix] pull 이후 Admin 오류 해결
  src/main/java/com/crude/travelcrew/domain/administer/controller/AdminController.java
  src/main/java/com/crude/travelcrew/domain/administer/service/AdminMemberService.java
Labels: fix

#109 [feat] 동행 게시물 상세조회
  src/main/java/com/crude/travelcrew/domain/crew/controller/CrewController.java
  src/main/java/com/crude/travelcrew/domain/crew/service/CrewService.java
Labels: feature

#118 [fix] 사용자가 쓴 여행기록 목록 조회 오류 수정
  src/main/java/com/crude/travelcrew/domain/member/controller/MyPageController.java
  src/main/java/com/crude/travelcrew/domain/member/service/MyPageService.java
  src/main/java/com/crude/travelcrew/domain/record/model/entity/Record.java
Labels: fix

#116 [Fix] 내가 쓴 동행 모집 조회 아이디 오류 수정
  src/main/java/com/crude/travelcrew/domain/crew/model/entity/Crew.java
Labels: fix

#121 [fix] 동행 글 삭제 수정
  src/main/java/com/crude/travelcrew/domain/crew/repository/CrewCommentRepository.java
  src/main/java/com/crude/travelcrew/domain/crew/repository/custom/CustomCrewCommentRepository.java
  src/main/java/com/crude/travelcrew/domain/crew/repository/custom/CustomCrewCommentRepositoryImpl.java
  src/main/java/com/crude/travelcrew/domain/crew/repository/custom/CustomCrewMemberRepository.java
  src/main/java/com/crude/travelcrew/domain/crew/repository/custom/CustomCrewMemberRepositoryImpl.java
  src/main/java/com/crude/travelcrew/domain/crew/service/CrewService.java
Labels: fix

#123 [feat] 동행 종료 후 리뷰 별점 작성
  src/main/java/com/crude/travelcrew/domain/crew/controller/CrewMemberController.java
  src/main/java/com/crude/travelcrew/domain/crew/controller/CrewReviewController.java
  src/main/java/com/crude/travelcrew/domain/crew/model/dto/CrewMemberRes.java
  src/main/java/com/crude/travelcrew/domain/crew/model/dto/CrewReviewReq.java
  src/main/java/com/crude/travelcrew/domain/crew/model/entity/HeartBeat.java
  src/main/java/com/crude/travelcrew/domain/crew/repository/CrewMemberRepository.java
  src/main/java/com/crude/travelcrew/domain/crew/repository/CrewRepository.java
  src/main/java/com/crude/travelcrew/domain/crew/repository/HeartBeatRepository.java
  src/main/java/com/crude/travelcrew/domain/crew/service/CrewMemberService.java
  src/main/java/com/crude/travelcrew/domain/crew/service/CrewMemberServiceImpl.java
  src/main/java/com/crude/travelcrew/domain/crew/service/CrewReviewService.java
  src/main/java/com/crude/travelcrew/domain/member/repository/MemberProfileRepository.java
  src/main/java/com/crude/travelcrew/global/error/type/CrewErrorCode.java
Labels: feature

#122 [feat] 이메일 인증 기능 구현
  src/main/java/com/crude/travelcrew/domain/email/controller/EmailController.java
  src/main/java/com/crude/travelcrew/domain/email/model/EmailMessage.java
  src/main/java/com/crude/travelcrew/domain/email/model/EmailSendReq.java
  src/main/java/com/crude/travelcrew/domain/email/model/EmailVerifyReq.java
  src/main/java/com/crude/travelcrew/domain/email/service/EmailSenderService.java
  src/main/java/com/crude/travelcrew/domain/email/service/EmailSenderServiceImpl.java
Labels: feature

#128 [rename] entity 및 dto 이름 변경
  src/main/java/com/crude/travelcrew/domain/crew/controller/ProposalController.java
  src/main/java/com/crude/travelcrew/domain/crew/model/constants/CrewMemberStatus.java
  src/main/java/com/crude/travelcrew/domain/crew/model/constants/ProposalStatus.java
  src/main/java/com/crude/travelcrew/domain/crew/model/dto/AddProposalReq.java
  src/main/java/com/crude/travelcrew/domain/crew/model/dto/CrewMemberRes.java
  src/main/java/com/crude/travelcrew/domain/crew/model/dto/ProposalRes.java
  src/main/java/com/crude/travelcrew/domain/crew/model/entity/Proposal.java
  src/main/java/com/crude/travelcrew/domain/crew/repository/CrewMemberRepository.java
  src/main/java/com/crude/travelcrew/domain/crew/repository/ProposalRepository.java
  src/main/java/com/crude/travelcrew/domain/crew/repository/custom/CustomCrewMemberRepository.java
  src/main/java/com/crude/travelcrew/domain/crew/repository/custom/CustomCrewMemberRepositoryImpl.java
  src/main/java/com/crude/travelcrew/domain/crew/repository/custom/CustomProposalRepository.java
  src/main/java/com/crude/travelcrew/domain/crew/repository/custom/CustomProposalRepositoryImpl.java
  src/main/java/com/crude/travelcrew/domain/crew/service/CrewMemberService.java
  src/main/java/com/crude/travelcrew/domain/crew/service/CrewService.java
  src/main/java/com/crude/travelcrew/domain/crew/service/ProposalService.java
  src/main/java/com/crude/travelcrew/domain/crew/service/ProposalServiceImpl.java
  src/main/java/com/crude/travelcrew/domain/email/model/EmailAuthCode.java
  src/main/java/com/crude/travelcrew/domain/member/controller/MyPageController.java
  src/main/java/com/crude/travelcrew/domain/member/service/MyPageService.java
  src/main/java/com/crude/travelcrew/global/config/JpaConfig.java
Labels: rename

#130 [feat] 동행 신청 승인 및 거절
  src/main/java/com/crude/travelcrew/domain/crew/controller/ProposalController.java
  src/main/java/com/crude/travelcrew/domain/crew/model/dto/EditProposalStatusReq.java
  src/main/java/com/crude/travelcrew/domain/crew/model/entity/Proposal.java
  src/main/java/com/crude/travelcrew/domain/crew/repository/custom/CustomProposalRepository.java
  src/main/java/com/crude/travelcrew/domain/crew/repository/custom/CustomProposalRepositoryImpl.java
  src/main/java/com/crude/travelcrew/domain/crew/service/ProposalService.java
  src/main/java/com/crude/travelcrew/domain/crew/service/ProposalServiceImpl.java
  src/main/java/com/crude/travelcrew/global/error/handler/GlobalExceptionHandler.java
  src/main/java/com/crude/travelcrew/global/error/type/CrewErrorCode.java
Labels: feature

#140 [feat] 알림 기능
  src/main/java/com/crude/travelcrew/domain/crew/controller/ProposalController.java
  src/main/java/com/crude/travelcrew/domain/crew/repository/custom/CustomProposalRepository.java
  src/main/java/com/crude/travelcrew/domain/crew/repository/custom/CustomProposalRepositoryImpl.java
  src/main/java/com/crude/travelcrew/domain/crew/service/ProposalService.java
  src/main/java/com/crude/travelcrew/domain/crew/service/ProposalServiceImpl.java
  src/main/java/com/crude/travelcrew/domain/notification/controller/NotificationController.java
  src/main/java/com/crude/travelcrew/domain/notification/handler/NotificationConsumer.java
  src/main/java/com/crude/travelcrew/domain/notification/handler/NotificationProducer.java
  src/main/java/com/crude/travelcrew/domain/notification/model/constants/NotificationType.java
  src/main/java/com/crude/travelcrew/domain/notification/model/dto/Message.java
  src/main/java/com/crude/travelcrew/domain/notification/model/dto/NotificationInfoRes.java
  src/main/java/com/crude/travelcrew/domain/notification/model/entity/Notification.java
  src/main/java/com/crude/travelcrew/domain/notification/repository/NotificationRepository.java
  src/main/java/com/crude/travelcrew/domain/notification/repository/custom/CustomNotificationRepository.java
  src/main/java/com/crude/travelcrew/domain/notification/repository/custom/CustomNotificationRepositoryImpl.java
  src/main/java/com/crude/travelcrew/domain/notification/service/NotificationService.java
  src/main/java/com/crude/travelcrew/domain/notification/service/NotificationServiceImpl.java
  src/main/java/com/crude/travelcrew/domain/notification/sse/SseConnection.java
  src/main/java/com/crude/travelcrew/domain/notification/sse/repository/ConnectionRepository.java
  src/main/java/com/crude/travelcrew/domain/notification/sse/repository/SseConnectionRepository.java
  src/main/java/com/crude/travelcrew/global/config/JpaConfig.java
  src/main/java/com/crude/travelcrew/global/security/jwt/JwtAuthFilter.java
Labels: feature

#139 [feat] 여행 기록 목록, 상세 조회에 현재 받은 좋아요 수 추가
  src/main/java/com/crude/travelcrew/domain/record/model/dto/GetRecordRes.java
  src/main/java/com/crude/travelcrew/domain/record/model/dto/RecordListRes.java
  src/main/java/com/crude/travelcrew/domain/record/repository/RecordHeartRepository.java
  src/main/java/com/crude/travelcrew/domain/record/repository/RecordRepository.java
  src/main/java/com/crude/travelcrew/domain/record/service/RecordServiceImpl.java
Labels: feature

#147 [feat] 로그인 한 회원 프로필 이미지, 닉네임 조회
  src/main/java/com/crude/travelcrew/domain/administer/controller/AdminController.java
  src/main/java/com/crude/travelcrew/domain/administer/service/AdminGetCrewService.java
  src/main/java/com/crude/travelcrew/domain/administer/service/AdminGetMemberService.java
  src/main/java/com/crude/travelcrew/domain/administer/service/AdminGetRecordService.java
  src/main/java/com/crude/travelcrew/domain/administer/service/AdminGetReportService.java
  src/main/java/com/crude/travelcrew/domain/crew/service/CrewScrapService.java
  src/main/java/com/crude/travelcrew/domain/crew/service/CrewService.java
  src/main/java/com/crude/travelcrew/domain/email/service/EmailSenderServiceImpl.java
  src/main/java/com/crude/travelcrew/domain/member/controller/MemberController.java
  src/main/java/com/crude/travelcrew/domain/member/controller/MyPageController.java
  src/main/java/com/crude/travelcrew/domain/member/model/dto/ProfileRes.java
  src/main/java/com/crude/travelcrew/domain/member/service/MemberService.java
  src/main/java/com/crude/travelcrew/domain/member/service/MyPageService.java
  src/main/java/com/crude/travelcrew/domain/notification/service/NotificationServiceImpl.java
  src/main/java/com/crude/travelcrew/domain/record/service/RecordServiceImpl.java
  src/main/java/com/crude/travelcrew/domain/report/service/ReportService.java
  src/main/java/com/crude/travelcrew/global/error/type/CommonErrorCode.java
  src/main/java/com/crude/travelcrew/global/error/type/CrewErrorCode.java
  src/main/java/com/crude/travelcrew/global/error/type/MemberErrorCode.java
Labels: feature, emergency

#144 [refactor] 회원 가입 시 중복 확인 절차 필요
  src/main/java/com/crude/travelcrew/domain/member/controller/MemberController.java
  src/main/java/com/crude/travelcrew/domain/member/repository/MemberRepository.java
  src/main/java/com/crude/travelcrew/domain/member/service/MemberService.java
  src/main/java/com/crude/travelcrew/global/config/SecurityConfig.java
  src/main/java/com/crude/travelcrew/global/error/type/MemberErrorCode.java
  src/main/java/com/crude/travelcrew/global/security/jwt/JwtAuthFilter.java
Labels: refactor

#135 [feat] 채팅기능 추가
  docker-compose.yml
  src/main/java/com/crude/travelcrew/domain/crew/controller/CrewController.java
  src/main/java/com/crude/travelcrew/domain/crew/controller/CrewMessageController.java
  src/main/java/com/crude/travelcrew/domain/crew/handler/ChatPreHandler.java
  src/main/java/com/crude/travelcrew/domain/crew/model/constants/MessageType.java
  src/main/java/com/crude/travelcrew/domain/crew/model/dto/CrewMessageReq.java
  src/main/java/com/crude/travelcrew/domain/crew/model/dto/CrewMessageRes.java
  src/main/java/com/crude/travelcrew/domain/crew/model/dto/CrewRes.java
  src/main/java/com/crude/travelcrew/domain/crew/model/entity/CrewMessage.java
  src/main/java/com/crude/travelcrew/domain/crew/repository/CrewMemberRepository.java
  src/main/java/com/crude/travelcrew/domain/crew/repository/CrewMessageRepository.java
  src/main/java/com/crude/travelcrew/domain/crew/service/CrewMessageService.java
  src/main/java/com/crude/travelcrew/domain/crew/service/CrewMessageServiceImpl.java
  src/main/java/com/crude/travelcrew/domain/crew/service/CrewService.java
  src/main/java/com/crude/travelcrew/domain/crew/service/CrewServiceImpl.java
  src/main/java/com/crude/travelcrew/domain/crew/service/ProposalServiceImpl.java
  src/main/java/com/crude/travelcrew/domain/member/model/entity/Member.java
  src/main/java/com/crude/travelcrew/global/config/WebConfig.java
  src/main/java/com/crude/travelcrew/global/config/WebSocketConfig.java
  src/main/java/com/crude/travelcrew/global/error/type/CrewErrorCode.java
Labels: feature

#149 [fix] merge 후 오류 수정
  src/main/java/com/crude/travelcrew/domain/crew/service/CrewService.java
  src/main/java/com/crude/travelcrew/domain/crew/service/CrewServiceImpl.java
  src/main/java/com/crude/travelcrew/global/error/type/MemberErrorCode.java
Labels: fix

#152 [refactor] spring security
  src/main/java/com/crude/travelcrew/domain/member/controller/MemberController.java
  src/main/java/com/crude/travelcrew/domain/member/model/dto/SignUpReq.java
  src/main/java/com/crude/travelcrew/global/config/SecurityConfig.java
  src/main/java/com/crude/travelcrew/global/security/jwt/JwtAuthFilter.java
Labels: feature

#153 [refactor] 관리자 페이지 신고회원 관련 수정
  src/main/java/com/crude/travelcrew/domain/administer/controller/AdminController.java
  src/main/java/com/crude/travelcrew/domain/administer/service/AdminMemberService.java
Labels: refactor

#156 [refactor] 동행 글, 여행 기록 전체 조회, 상세 조회 관련 코드 수정
  src/main/java/com/crude/travelcrew/domain/crew/controller/CrewController.java
  src/main/java/com/crude/travelcrew/domain/crew/model/dto/CrewCommentRes.java
  src/main/java/com/crude/travelcrew/domain/crew/model/dto/CrewRes.java
  src/main/java/com/crude/travelcrew/domain/crew/model/dto/ProposalRes.java
  src/main/java/com/crude/travelcrew/domain/crew/model/entity/CrewComment.java
  src/main/java/com/crude/travelcrew/domain/crew/repository/CrewRepository.java
  src/main/java/com/crude/travelcrew/domain/crew/service/CrewService.java
  src/main/java/com/crude/travelcrew/domain/crew/service/CrewServiceImpl.java
  src/main/java/com/crude/travelcrew/domain/member/model/entity/Member.java
  src/main/java/com/crude/travelcrew/domain/record/controller/RecordController.java
  src/main/java/com/crude/travelcrew/domain/record/model/dto/GetRecordRes.java
  src/main/java/com/crude/travelcrew/domain/record/model/dto/RecordCommentRes.java
  src/main/java/com/crude/travelcrew/domain/record/model/dto/RecordListRes.java
  src/main/java/com/crude/travelcrew/domain/record/repository/RecordRepository.java
  src/main/java/com/crude/travelcrew/domain/record/service/RecordService.java
  src/main/java/com/crude/travelcrew/domain/record/service/RecordServiceImpl.java
Labels: refactor

#155 [feat] 관리자 페이지 접근 권한 설정
  src/main/java/com/crude/travelcrew/domain/administer/controller/AdminController.java
  src/main/java/com/crude/travelcrew/domain/crew/service/CrewServiceImpl.java
  src/main/java/com/crude/travelcrew/global/config/SecurityConfig.java
  src/main/java/com/crude/travelcrew/global/security/jwt/JwtAuthFilter.java
Labels: refactor
